import { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Brain, Check, ChevronRight, Crown, Flame, Gauge, Keyboard, MousePointer2, Music2, Target, Timer, Trophy, Volume2, Zap } from 'lucide-react';
import './style.css';

type Mode = 'reaction' | 'click' | 'aim' | 'keyboard' | 'rhythm' | 'memory' | 'numbers' | 'color' | 'mouse' | 'arrows' | 'math' | 'odd' | 'track' | 'switch' | 'drag' | 'sequence';
type Game = { id: string; name: string; category: string; desc: string; icon: typeof Zap; record: string; attempts: string; accent: string; mode: Mode; lowerIsBetter?: boolean };
type GameResult = { value: string; accuracy?: string; details?: [string, string][] };

const games: Game[] = [
  { id: 'reaction', lowerIsBetter: true, name: 'Тест реакции', category: 'РЕАКЦИЯ', desc: 'Нажми в момент появления сигнала.', icon: Zap, record: '142 мс', attempts: '28,4 тыс. игр', accent: '#bdff64', mode: 'reaction' },
  { id: 'click-speed', name: 'Скорость кликов', category: 'КЛИКИ', desc: 'Выжми максимум кликов в секунду.', icon: MousePointer2, record: '18,2 CPS', attempts: '18,9 тыс. игр', accent: '#ff9d5c', mode: 'click' },
  { id: 'aim', name: 'Тренировка точности', category: 'ТОЧНОСТЬ', desc: 'Поражай цели до их исчезновения.', icon: Target, record: '96,8%', attempts: '16,2 тыс. игр', accent: '#8cf0ff', mode: 'aim' },
  { id: 'keyboard', name: 'Клавиатурный рывок', category: 'СКОРОСТЬ', desc: 'Напечатай последовательность без пауз.', icon: Keyboard, record: '142 WPM', attempts: '14,5 тыс. игр', accent: '#d5a6ff', mode: 'keyboard' },
  { id: 'rhythm', name: 'Ритм-тап', category: 'РИТМ', desc: 'Поймай идеальный момент пульса.', icon: Music2, record: '99,4%', attempts: '12,1 тыс. игр', accent: '#ff6b9a', mode: 'rhythm' },
  { id: 'memory', name: 'Сетка памяти', category: 'ПАМЯТЬ', desc: 'Повтори паттерн, пока он становится сложнее.', icon: Brain, record: 'Уровень 18', attempts: '9,8 тыс. игр', accent: '#ffc85c', mode: 'memory' },
  { id: 'mouse-speed', lowerIsBetter: true, name: 'Поток мыши', category: 'КООРДИНАЦИЯ', desc: 'Пройди ворота плавным движением.', icon: Gauge, record: '4,82 с', attempts: '7,4 тыс. игр', accent: '#83a6ff', mode: 'mouse' },
  { id: 'keyboard-reaction', name: 'Стрелочный рефлекс', category: 'КЛАВИАТУРА', desc: 'Повторяй направления на скорости.', icon: ChevronRight, record: '286 очков', attempts: '6,3 тыс. игр', accent: '#a0ffbd', mode: 'arrows' },
  { id: 'numbers', lowerIsBetter: true, name: 'Числовая последовательность', category: 'СКОРОСТЬ', desc: 'Найди числа в правильном порядке.', icon: Timer, record: '3,18 с', attempts: '8,9 тыс. игр', accent: '#ffbb75', mode: 'numbers' },
  { id: 'color-match', name: 'Совпадение цветов', category: 'ФОКУС', desc: 'Доверяй цвету, а не прочитанному слову.', icon: Target, record: '1 240 очков', attempts: '5,6 тыс. игр', accent: '#ff86cd', mode: 'color' },
  { id: 'quick-math', lowerIsBetter: true, name: 'Быстрый счёт', category: 'МЫШЛЕНИЕ', desc: 'Решай простые примеры без задержки.', icon: Brain, record: '6,20 с', attempts: '4,1 тыс. игр', accent: '#7ee5bd', mode: 'math' },
  { id: 'odd-one-out', lowerIsBetter: true, name: 'Найди лишнее', category: 'ВНИМАНИЕ', desc: 'Найди отличающуюся фигуру в сетке.', icon: Target, record: '1,84 с', attempts: '3,8 тыс. игр', accent: '#ffcd79', mode: 'odd' },
  { id: 'target-track', name: 'Следи за целью', category: 'КООРДИНАЦИЯ', desc: 'Удерживай курсор на движущейся цели.', icon: MousePointer2, record: '98,2%', attempts: '3,2 тыс. игр', accent: '#7fabff', mode: 'track' },
  { id: 'fast-switch', name: 'Быстрое переключение', category: 'РЕШЕНИЕ', desc: 'Нажимай только на круги.', icon: Zap, record: '680 очков', attempts: '2,9 тыс. игр', accent: '#f095d0', mode: 'switch' },
  { id: 'drag-race', lowerIsBetter: true, name: 'Гонка перетаскивания', category: 'ТОЧНОСТЬ', desc: 'Перетащи объект в правильную зону.', icon: Gauge, record: '2,40 с', attempts: '2,6 тыс. игр', accent: '#a1e981', mode: 'drag' },
  { id: 'sequence', name: 'Запомни порядок', category: 'ПАМЯТЬ', desc: 'Повтори последовательность фигур.', icon: Brain, record: 'Уровень 12', attempts: '2,4 тыс. игр', accent: '#b9a3ff', mode: 'sequence' }
];
const leaderboard = [['Мира', '12 482'], ['н0ва', '12 108'], ['кайзо', '11 994'], ['ты', '11 680'], ['Ленн', '11 251']];
const arrowKeys = ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'] as const;
const arrowLabels: Record<(typeof arrowKeys)[number], string> = { ArrowUp: '↑', ArrowDown: '↓', ArrowLeft: '←', ArrowRight: '→' };
const saved = (id: string) => { try { return JSON.parse(localStorage.getItem(`pulse:${id}`) || '[]') as number[]; } catch { return []; } };

function Header({ page, setPage }: { page: string; setPage: (page: string) => void }) { return <><header><button className="brand" onClick={() => setPage('home')}><i /> PULSE</button><nav>{[['games', 'Игры'], ['leaderboard', 'Рейтинг'], ['daily', 'Испытание дня']].map(([key, label]) => <button className={page === key ? 'active' : ''} onClick={() => setPage(key)} key={key}>{label}</button>)}</nav><div className="user"><span className="level">УР. 12 <b>Собранный</b></span><button onClick={() => setPage('profile')} className="avatar" aria-label="Открыть профиль">К</button></div></header><div className="mobile-nav">{[['home', 'Главная'], ['games', 'Игры'], ['leaderboard', 'Рейтинг'], ['profile', 'Профиль']].map(([key, label]) => <button onClick={() => setPage(key)} className={page === key ? 'active' : ''} key={key}>{label}</button>)}</div></> }
function Card({ g, onPlay }: { g: Game; onPlay: () => void }) { const Icon = g.icon; return <article className="game-card" style={{ '--accent': g.accent } as React.CSSProperties} onClick={onPlay} tabIndex={0} onKeyDown={event => event.key === 'Enter' && onPlay()}><div className="card-top"><span>{g.category}</span><Icon size={19} /></div><div className="game-preview"><div className={`orb ${g.mode}`} /><div className="preview-lines" /></div><h3>{g.name}</h3><p>{g.desc}</p><footer><span>ЛУЧШИЙ <b>{g.record}</b></span><span>{g.attempts}</span></footer></article> }
function Home({ setPage, play }: { setPage: (page: string) => void; play: (game: Game) => void }) { return <main><section className="hero"><div className="eyebrow"><span /> ЛАБОРАТОРИЯ ЧЕЛОВЕЧЕСКОЙ ПРОИЗВОДИТЕЛЬНОСТИ</div><h1>Насколько<br />ты <em>быстр?</em></h1><p>Проверяй реакцию, скорость, точность и координацию в коротких соревновательных испытаниях.</p><div className="hero-actions"><button className="primary" onClick={() => play(games[0])}>Начать испытание <ArrowRight /></button><button className="quiet" onClick={() => setPage('games')}>Все игры</button></div><div className="hero-score"><div><small>ТВОЙ SKILL SCORE</small><strong>782</strong><span>+24 за эту неделю</span></div><div className="radar">✦</div><div className="score-list"><span>РЕАКЦИЯ <b>820</b></span><span>ТОЧНОСТЬ <b>910</b></span><span>ПАМЯТЬ <b>680</b></span></div></div></section><section className="featured"><div><span className="eyebrow"><span /> ИСПЫТАНИЕ ДНЯ</span><h2>Один шанс.<br /><em>Покажи класс.</em></h2><p>Тест реакции · только одна попытка<br />До обновления 08:42:16</p><button className="primary" onClick={() => play(games[0])}>Принять вызов <ArrowRight /></button></div><div className="daily-number"><b>147</b><span>МС НУЖНО ПОБИТЬ</span><i>ТОП 5%</i></div></section><section className="section-title"><div><span className="eyebrow">ПОПУЛЯРНЫЕ ИСПЫТАНИЯ</span><h2>Созданы для нового рекорда.</h2></div><button className="text-btn" onClick={() => setPage('games')}>Все 16 игр <ArrowRight size={16} /></button></section><section className="cards">{games.slice(0, 6).map(g => <Card g={g} onPlay={() => play(g)} key={g.id} />)}</section><section className="split"><div className="leader"><div className="section-title"><div><span className="eyebrow">МИРОВОЙ РЕЙТИНГ</span><h2>Счёт идёт на миллисекунды.</h2></div><Trophy /></div>{leaderboard.map((row, index) => <div className={`rank ${row[0] === 'ты' ? 'is-you' : ''}`} key={row[0]}><b>0{index + 1}</b><div className="avatar mini">{row[0][0]}</div><span>{row[0]}</span><strong>{row[1]} <small>ОЧКОВ</small></strong></div>)}</div><div className="achievement"><Crown size={28} /><span className="eyebrow">СЛЕДУЮЩЕЕ ДОСТИЖЕНИЕ</span><h3>НЕОСТАНОВИМЫЙ</h3><p>Поддерживай серию 7 дней. Уже пройдено 5.</p><div className="progress"><i style={{ width: '71%' }} /></div><small>5 / 7 ДНЕЙ</small></div></section><section className="cta"><span className="eyebrow">ТВОЙ НОВЫЙ РЕКОРД</span><h2>Маленькие игры.<br /><em>Большой прогресс.</em></h2><button className="primary" onClick={() => setPage('games')}>Начать тренировку <ArrowRight /></button></section></main> }
function Result({ result, game, replay, close, leaderboard }: { result: GameResult; game: Game; replay: () => void; close: () => void; leaderboard: () => void }) { const [notice, setNotice] = useState(''); const share = async () => { const text = `Я показал результат ${result.value} в игре «${game.name}» на PULSE.`; try { if (navigator.share) await navigator.share({ title: 'PULSE', text }); else { await navigator.clipboard?.writeText(text); setNotice('Результат скопирован'); } } catch { setNotice('Не удалось поделиться результатом'); } }; return <div className="result"><div className="result-icon"><Trophy /></div><span className="eyebrow">ТВОЙ РЕЗУЛЬТАТ</span><h2>{result.value}</h2><p>Ты быстрее, чем <b>82%</b> игроков</p>{result.details && <div className="result-details">{result.details.map(([label, value]) => <span key={label}>{label}<b>{value}</b></span>)}</div>}<div className="pb"><Check /> НОВЫЙ ЛИЧНЫЙ РЕКОРД <span>+18 XP</span></div><div className="result-stats"><span>МИРОВОЙ РАНГ <b>#1 284</b></span><span>ТОЧНОСТЬ <b>{result.accuracy || '96,8%'}</b></span><span>СЕРИЯ <b>4 ДНЯ</b></span></div><button className="primary" onClick={replay}>Играть ещё <ArrowRight /></button><div className="result-actions"><button className="quiet" onClick={leaderboard}>Таблица лидеров</button><button className="quiet" onClick={share}>Поделиться</button></div><button className="quiet" onClick={close}>Вернуться к играм</button>{notice && <small className="notice">{notice}</small>}<small>Создай аккаунт, чтобы сохранить результат.</small></div> }
function GameFrame({ game, back, children }: { game: Game; back: () => void; children: React.ReactNode }) { const [sound, setSound] = useState(() => localStorage.getItem('pulse:sound') !== 'off'); const toggle = () => { const next = !sound; setSound(next); localStorage.setItem('pulse:sound', next ? 'on' : 'off'); if (next) { try { const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain(); gain.gain.value = .025; oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .06); } catch { /* audio is optional */ } } }; return <main className="game-page"><div className="game-head"><button className="back" onClick={back}>← Выйти</button><div><span>{game.category}</span><b>{game.name}</b></div><button className="sound" onClick={toggle} aria-pressed={sound}><Volume2 size={16} /> Звук: {sound ? 'вкл' : 'выкл'}</button></div>{children}</main> }

function GamePlay({ game, back, showLeaderboard }: { game: Game; back: () => void; showLeaderboard: () => void }) {
  const [phase, setPhase] = useState<'idle' | 'countdown' | 'playing' | 'result'>('idle');
  const [countdown, setCountdown] = useState(3); const [result, setResult] = useState<GameResult | null>(null);
  const [clicks, setClicks] = useState(0); const [target, setTarget] = useState({ x: 50, y: 50 }); const [hits, setHits] = useState(0);
  const [reactionReady, setReactionReady] = useState(false); const [typed, setTyped] = useState(''); const [memoryVisible, setMemoryVisible] = useState(true); const [memoryProgress, setMemoryProgress] = useState(0);
  const [arrow, setArrow] = useState<(typeof arrowKeys)[number]>('ArrowUp'); const [arrowIndex, setArrowIndex] = useState(0); const [arrowErrors, setArrowErrors] = useState(0); const [arrowNotice, setArrowNotice] = useState('');
  const timers = useRef<number[]>([]); const clicksRef = useRef(0); const startTime = useRef(0); const signalTime = useRef(0); const arrowTime = useRef(0); const arrowTimes = useRef<number[]>([]); const ending = useRef(false);
  const clearTimers = useCallback(() => { timers.current.forEach(window.clearTimeout); timers.current = []; }, []);
  const schedule = useCallback((callback: () => void, delay: number) => { const id = window.setTimeout(() => { timers.current = timers.current.filter(timer => timer !== id); callback(); }, delay); timers.current.push(id); return id; }, []);
  useEffect(() => () => clearTimers(), [clearTimers]);
  const finish = useCallback((next: GameResult) => { if (ending.current) return; ending.current = true; clearTimers(); setResult(next); setPhase('result'); try { const score = Number.parseFloat(next.value.replace(',', '.')); if (Number.isFinite(score)) localStorage.setItem(`pulse:${game.id}`, JSON.stringify([...saved(game.id), score].slice(-20))); } catch { /* local storage is optional */ } }, [clearTimers, game.id]);
  const reset = useCallback(() => { clearTimers(); ending.current = false; setResult(null); setClicks(0); clicksRef.current = 0; setHits(0); setTarget({ x: 50, y: 50 }); setReactionReady(false); setTyped(''); setMemoryVisible(true); setMemoryProgress(0); setArrowIndex(0); setArrowErrors(0); setArrowNotice(''); arrowTimes.current = []; setPhase('idle'); }, [clearTimers]);
  const startPlaying = useCallback(() => { setPhase('playing'); startTime.current = performance.now(); if (game.mode === 'reaction') schedule(() => { signalTime.current = performance.now(); setReactionReady(true); }, 1200 + Math.random() * 1500); if (game.mode === 'click') schedule(() => { const elapsed = Math.max((performance.now() - startTime.current) / 1000, 0.001); finish({ value: `${(clicksRef.current / elapsed).toFixed(1).replace('.', ',')} CPS`, details: [['КЛИКОВ', String(clicksRef.current)], ['ВРЕМЯ', `${elapsed.toFixed(2).replace('.', ',')} с`]] }); }, 5000); if (game.mode === 'memory') schedule(() => setMemoryVisible(false), 1200); if (game.mode === 'arrows') { const next = arrowKeys[Math.floor(Math.random() * arrowKeys.length)]; setArrow(next); } }, [finish, game.mode, schedule]);
  const begin = () => { if (phase !== 'idle') return; ending.current = false; setCountdown(3); setPhase('countdown'); };
  useEffect(() => { if (phase !== 'countdown') return; const id = window.setTimeout(() => { if (countdown === 1) startPlaying(); else setCountdown(value => value - 1); }, 700); return () => window.clearTimeout(id); }, [countdown, phase, startPlaying]);
  useEffect(() => { if (phase === 'playing' && game.mode === 'arrows') arrowTime.current = performance.now(); }, [arrow, arrowIndex, game.mode, phase]);
  useEffect(() => { if (phase !== 'playing') return; const onKey = (event: KeyboardEvent) => { if (game.mode === 'keyboard' && event.key === 'Enter' && typed.trim()) { const elapsed = Math.max((performance.now() - startTime.current) / 60000, 0.001); const words = typed.trim().split(/\s+/).length; finish({ value: `${Math.round(words / elapsed)} WPM`, accuracy: '100%', details: [['ВРЕМЯ', `${((performance.now() - startTime.current) / 1000).toFixed(2).replace('.', ',')} с`], ['ОШИБКИ', '0']] }); } if (game.mode === 'rhythm' && event.code === 'Space') { event.preventDefault(); finish({ value: '94% точности', accuracy: '94%', details: [['ИДЕАЛЬНО', '18'], ['ПРОМАХИ', '2']] }); } if (game.mode === 'arrows' && arrowKeys.includes(event.key as (typeof arrowKeys)[number])) { event.preventDefault(); const expected = arrow; const correct = event.key === expected; const reaction = performance.now() - arrowTime.current; if (correct) arrowTimes.current.push(reaction); else setArrowErrors(value => value + 1); setArrowNotice(correct ? 'Верно' : 'Ошибка'); const nextIndex = arrowIndex + 1; if (nextIndex >= 6) { const values = arrowTimes.current.concat(correct ? [reaction] : []); const average = values.length ? Math.round(values.reduce((sum, value) => sum + value, 0) / values.length) : 0; const accuracy = Math.round((values.length / 6) * 100); finish({ value: `${Math.max(0, values.length * 50 - (arrowErrors + (correct ? 0 : 1)) * 10)} очков`, accuracy: `${accuracy}%`, details: [['СРЕДНЯЯ РЕАКЦИЯ', `${average} мс`], ['ЛУЧШАЯ РЕАКЦИЯ', `${values.length ? Math.round(Math.min(...values)) : 0} мс`], ['ОШИБКИ', String(arrowErrors + (correct ? 0 : 1))] ] }); return; } setArrowIndex(nextIndex); const next = arrowKeys[Math.floor(Math.random() * arrowKeys.length)]; setArrow(next); schedule(() => setArrowNotice(''), 350); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [arrow, arrowErrors, arrowIndex, finish, game.mode, phase, schedule, typed]);
  const reactionClick = () => { if (phase !== 'playing') return; if (!reactionReady) { finish({ value: 'Слишком рано!', accuracy: '—', details: [['ПОДСКАЗКА', 'Дождись зелёного сигнала']] }); return; } const value = Math.max(0, Math.round(performance.now() - signalTime.current)); const history = [...saved('reaction'), value]; const best = Math.min(...history); const average = Math.round(history.reduce((sum, item) => sum + item, 0) / history.length); finish({ value: `${value} мс`, details: [['ЛУЧШИЙ РЕЗУЛЬТАТ', `${best} мс`], ['СРЕДНИЙ РЕЗУЛЬТАТ', `${average} мс`]] }); };
  const aimHit = () => { if (phase !== 'playing') return; const next = hits + 1; setHits(next); if (next >= 8) { finish({ value: '96,8%', accuracy: '96,8%', details: [['ПОПАДАНИЯ', '8 / 8'], ['КОМБО', '8']] }); return; } setTarget({ x: 10 + Math.random() * 80, y: 12 + Math.random() * 72 }); };
  const click = () => { if (phase === 'playing' && !ending.current) setClicks(value => { const next = value + 1; clicksRef.current = next; return next; }); };
  if (phase === 'result' && result) return <GameFrame game={game} back={back}><div className="game-stage"><Result result={result} game={game} replay={reset} close={back} leaderboard={showLeaderboard} /></div></GameFrame>;
  return <GameFrame game={game} back={back}><div className="game-stage">{phase === 'idle' && <><span className="eyebrow">{game.category} · {game.name}</span><h2>{game.name}</h2><p>{game.desc}</p><button className="primary" onClick={begin}>Начать испытание <ArrowRight /></button><small>Высокоточное измерение · Звук включён <Volume2 size={13} /></small></>}{phase === 'countdown' && <div className="countdown">{countdown}<small>ПРИГОТОВЬСЯ</small></div>}{phase === 'playing' && <PlayUI game={game} reactionReady={reactionReady} reactionClick={reactionClick} clicks={clicks} click={click} target={target} hits={hits} aimHit={aimHit} startedAt={startTime.current} typed={typed} setTyped={setTyped} memoryVisible={memoryVisible} memoryProgress={memoryProgress} setMemoryProgress={setMemoryProgress} finish={finish} arrow={arrow} arrowIndex={arrowIndex} arrowNotice={arrowNotice} />}</div></GameFrame>;
}
function PlayUI({ game, reactionReady, reactionClick, clicks, click, target, hits, aimHit, startedAt, typed, setTyped, memoryVisible, memoryProgress, setMemoryProgress, finish, arrow, arrowIndex, arrowNotice }: { game: Game; reactionReady: boolean; reactionClick: () => void; clicks: number; click: () => void; target: { x: number; y: number }; hits: number; aimHit: () => void; startedAt: number; typed: string; setTyped: (value: string) => void; memoryVisible: boolean; memoryProgress: number; setMemoryProgress: (value: number) => void; finish: (result: GameResult) => void; arrow: string; arrowIndex: number; arrowNotice: string }) {
  if (game.mode === 'reaction') return <button className={`reaction-zone ${reactionReady ? 'live' : ''}`} onClick={reactionClick}>{reactionReady ? 'ЖМИ!' : 'Жди'}<small>{reactionReady ? 'Нажми сейчас' : 'Дождись сигнала'}</small></button>;
  if (game.mode === 'click') return <button className="click-zone" onClick={click}><b>{clicks}</b><span>КЛИКОВ</span><small>Нажимай в любом месте</small></button>;
  if (game.mode === 'aim') return <div className="aim-zone"><div className="aim-stats">СЧЁТ <b>{hits}/8</b> · КОМБО <b>{hits}</b></div><button aria-label="Цель" onClick={aimHit} className="target" style={{ left: `${target.x}%`, top: `${target.y}%` }} /></div>;
  if (game.mode === 'keyboard') return <div className="type-zone"><span>НАПЕЧАТАЙ ФРАЗУ</span><b>фокус · быстрее · точнее</b><input autoFocus value={typed} onChange={event => setTyped(event.target.value)} placeholder="Нажми Enter после ввода" /></div>;
  if (game.mode === 'rhythm') return <div className="rhythm-zone"><span>НАЖМИ ПРОБЕЛ В РИТМ</span><div className="timing"><i /><b /></div><strong>● · · · ● · · ·</strong></div>;
  if (game.mode === 'memory') return <div className="memory-wrap"><p>{memoryVisible ? 'Запомни подсвеченные клетки' : 'Повтори паттерн'}</p><div className="memory-grid">{Array.from({ length: 9 }, (_, index) => <button aria-label={`Клетка ${index + 1}`} className={memoryVisible && [0, 2, 4].includes(index) ? 'lit' : ''} onClick={() => { if (memoryVisible) return; if ([0, 2, 4][memoryProgress] === index) { const next = memoryProgress + 1; setMemoryProgress(next); if (next === 3) finish({ value: 'Уровень 4', accuracy: '100%', details: [['СЕРИЯ', '3'], ['ОЧКИ', '300']] }); } else finish({ value: 'Уровень 2', accuracy: '67%', details: [['СЕРИЯ', String(memoryProgress)], ['ОЧКИ', String(memoryProgress * 100)]] }); }} key={index} />)}</div></div>;
  if (game.mode === 'numbers') { return <div className="number-grid">{[4, 1, 6, 3, 2, 5, 7, 8, 9].map(number => <button onClick={() => { const expected = memoryProgress + 1; if (number === expected) { const next = expected + 1; setMemoryProgress(expected); if (number === 9) finish({ value: `${Math.max(.01, (performance.now() - startedAt) / 1000).toFixed(2).replace('.', ',')} с`, details: [['ЧИСЕЛ', '9'], ['ОШИБКИ', '0']] }); } }} key={number}>{number}</button>)}</div>; }
  if (game.mode === 'color') return <div className="color-zone"><strong style={{ color: '#8cf0ff' }}>КРАСНЫЙ</strong><p>Выбери цвет слова</p><div>{['СИНИЙ', 'КРАСНЫЙ', 'ЗЕЛЁНЫЙ', 'ЖЁЛТЫЙ'].map(choice => <button onClick={() => finish(choice === 'СИНИЙ' ? { value: '1 240 очков', accuracy: '100%', details: [['ПРАВИЛЬНО', '1'], ['ОШИБКИ', '0']] } : { value: 'Промах', accuracy: '0%', details: [['ПРАВИЛЬНО', '0'], ['ОШИБКИ', '1']] })} key={choice}>{choice}</button>)}</div></div>;
  if (game.mode === 'mouse') return <div className="mouse-zone"><p>Проведи курсор через ворота по порядку</p>{[1, 2, 3, 4].map(number => <button onMouseEnter={() => { if (number === memoryProgress + 1) { const next = memoryProgress + 1; setMemoryProgress(next); if (next === 4) finish({ value: '4,82 с', accuracy: '100%', details: [['ОШИБКИ', '0'], ['ТОЧНОСТЬ', '100%']] }); } }} key={number}>{number}</button>)}</div>;
  if (game.mode === 'math') return <div className="type-zone"><span>РЕШИ ПРИМЕР</span><b>17 + 24 = ?</b><input autoFocus inputMode="numeric" placeholder="Введи ответ и нажми Enter" onKeyDown={event => { if (event.key === 'Enter') finish({ value: event.currentTarget.value === '41' ? '6,20 с' : 'Ошибка', accuracy: event.currentTarget.value === '41' ? '100%' : '0%', details: [['ПРАВИЛЬНО', event.currentTarget.value === '41' ? '1' : '0'], ['СЕРИЯ', event.currentTarget.value === '41' ? '1' : '0']] }); }} /></div>;
  if (game.mode === 'odd') return <div className="odd-grid">{Array.from({ length: 16 }, (_, index) => <button onClick={() => index === 11 ? finish({ value: '1,84 с', accuracy: '100%', details: [['УРОВЕНЬ', '1'], ['ОШИБКИ', '0']] }) : finish({ value: 'Промах', accuracy: '0%', details: [['УРОВЕНЬ', '1'], ['ОШИБКИ', '1']] })} className={index === 11 ? 'odd' : ''} aria-label={index === 11 ? 'Отличающаяся фигура' : 'Фигура'} key={index}>◆</button>)}</div>;
  if (game.mode === 'track') return <div className="track-zone"><p>Удерживай курсор над целью</p><button className="track-target" onMouseEnter={() => window.setTimeout(() => finish({ value: '98,2%', accuracy: '98,2%', details: [['УДЕРЖАНИЕ', '5,00 с'], ['ПОТЕРИ ЦЕЛИ', '0']] }), 1500)} aria-label="Движущаяся цель" /></div>;
  if (game.mode === 'switch') return <div className="switch-zone"><p>Нажимай только на круги</p><div>{['●', '▲', '●', '■'].map((shape, index) => <button onClick={() => shape === '●' ? (index === 2 ? finish({ value: '680 очков', accuracy: '100%', details: [['ПРАВИЛЬНО', '2'], ['ОШИБКИ', '0']] }) : undefined) : finish({ value: 'Промах', accuracy: '0%', details: [['ПРАВИЛЬНО', '0'], ['ОШИБКИ', '1']] })} key={index}>{shape}</button>)}</div></div>;
  if (game.mode === 'drag') return <div className="drag-zone"><p>Перетащи зелёный объект в отмеченную область</p><div draggable onDragEnd={() => finish({ value: '2,40 с', accuracy: '100%', details: [['ТОЧНОСТЬ', '100%'], ['ОШИБКИ', '0']] })} className="draggable">●</div><div className="drop-zone" onDragOver={event => event.preventDefault()} onDrop={() => finish({ value: '2,40 с', accuracy: '100%', details: [['ТОЧНОСТЬ', '100%'], ['ОШИБКИ', '0']] })}>СЮДА</div></div>;
  if (game.mode === 'sequence') return <div className="sequence-zone"><p>Запомни и повтори порядок: ● ▲ ■ ◆</p><div>{['●', '▲', '■', '◆'].map((shape, index) => <button onClick={() => index === memoryProgress ? (index === 3 ? finish({ value: 'Уровень 4', accuracy: '100%', details: [['ДЛИНА', '4'], ['СЕРИЯ', '4']] }) : setMemoryProgress(index + 1)) : finish({ value: 'Уровень 1', accuracy: '0%', details: [['ДЛИНА', String(memoryProgress)], ['ОШИБКИ', '1']] })} key={shape}>{shape}</button>)}</div></div>;
  return <div className="arrows-zone"><span>Нажми нужную стрелку на клавиатуре</span><strong>{arrowLabels[arrow as keyof typeof arrowLabels]}</strong><p>{arrowNotice || `СТРЕЛКА ${arrowIndex + 1} ИЗ 6`}</p></div>;
}
function Games({ play }: { play: (game: Game) => void }) { const [filter, setFilter] = useState('Все игры'); const filters = ['Все игры', 'Реакция', 'Точность', 'Скорость', 'Память']; const shown = filter === 'Все игры' ? games : games.filter(game => game.category === filter.toUpperCase()); return <main className="listing"><span className="eyebrow">БИБЛИОТЕКА ИСПЫТАНИЙ</span><h1>Найди своё<br /><em>преимущество.</em></h1><p>Шестнадцать точных тестов, чтобы раскрыть разные стороны твоей производительности.</p><div className="filters">{filters.map(item => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><section className="cards all">{shown.map(game => <Card g={game} onPlay={() => play(game)} key={game.id} />)}</section>{shown.length === 0 && <p className="empty">В этой категории пока нет испытаний.</p>}</main> }
function Leaderboard() { const [period, setPeriod] = useState('all'); const [gameId, setGameId] = useState(new URLSearchParams(window.location.search).get('game') || 'all'); const game = games.find(item => item.id === gameId); const raw = game ? saved(game.id) : []; const mock = game?.lowerIsBetter ? [142, 147, 151, 158] : [15.4, 14.8, 13.9, 12.7]; const scores = [...mock, ...raw].filter(Number.isFinite).sort((a, b) => game?.lowerIsBetter ? a - b : b - a).slice(0, period === 'today' ? 4 : period === 'week' ? 6 : 8); return <main className="listing leaderboard-page"><span className="eyebrow">ЖИВОЙ РЕЙТИНГ</span><h1>Сравни себя<br />со <em>всем миром.</em></h1><div className="leader-controls"><label>Игра<select value={gameId} onChange={event => { setGameId(event.target.value); window.history.replaceState({}, '', event.target.value === 'all' ? '/leaderboard' : `/leaderboard?game=${event.target.value}`); }}><option value="all">Все игры</option>{games.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="board-tabs">{[['today', 'Сегодня'], ['week', 'Неделя'], ['all', 'За всё время']].map(([key, label]) => <button className={period === key ? 'active' : ''} onClick={() => setPeriod(key)} key={key}>{label}</button>)}</div></div><div className="board"><div className="board-head"><span>МЕСТО</span><span>ИГРОК</span><span>{game?.lowerIsBetter ? 'РЕЗУЛЬТАТ' : game ? 'РЕЗУЛЬТАТ' : 'SKILL SCORE'}</span><span>СЕРИЯ</span></div>{scores.map((score, index) => <div className="board-row" key={`${score}-${index}`}><b>0{index + 1}</b><div className="avatar">{index === 3 ? 'Т' : leaderboard[index % leaderboard.length][0][0]}</div><strong>{index === 3 ? 'ты' : leaderboard[index % leaderboard.length][0]} {index === 3 && <small>ТЫ</small>}</strong><span>{game?.lowerIsBetter ? `${String(score).replace('.', ',')} мс` : gameId === 'click-speed' ? `${String(score).replace('.', ',')} CPS` : String(score).replace('.', ',')}</span><span><Flame size={15} /> {Math.max(1, 8 - index)} дн.</span></div>)}</div></main> }
function Profile() { const [editing, setEditing] = useState(false); const [nickname, setNickname] = useState(() => localStorage.getItem('pulse:nickname') || 'кира'); const completed = games.reduce((sum, game) => sum + saved(game.id).length, 0); return <main className="listing profile"><div className="profile-intro"><div className="avatar big">К</div><div><span className="eyebrow">ПРОФИЛЬ ИГРОКА</span><h1>{editing ? <input className="name-input" value={nickname} onChange={event => setNickname(event.target.value)} /> : nickname}<span>.pulse</span></h1><p>Собранный · Играет с сентября 2026</p></div><button className="quiet" onClick={() => { if (editing) localStorage.setItem('pulse:nickname', nickname.trim() || 'кира'); setEditing(value => !value); }}>{editing ? 'Сохранить' : 'Изменить профиль'}</button></div><section className="profile-score"><div><span>SKILL SCORE</span><strong>782</strong><small>ТОП 18% · +24 ЗА НЕДЕЛЮ</small></div><div className="radar large">✦</div><div className="meters">{[['Реакция', 82], ['Скорость', 74], ['Точность', 91], ['Память', 68], ['Ритм', 76]].map(([name, value]) => <label key={String(name)}>{name} <i><b style={{ width: `${value}%` }} /></i> {value}0</label>)}</div></section><div className="metrics">{[[String(Math.max(42, completed)), 'СЫГРАНО ИГР'], ['214 мс', 'ЛУЧШАЯ РЕАКЦИЯ'], ['87%', 'СР. ТОЧНОСТЬ'], ['5 ДНЕЙ', 'ТЕКУЩАЯ СЕРИЯ']].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><section className="achievement-row"><span className="eyebrow">ДОСТИЖЕНИЯ · 6/24</span><div>{['ПЕРВАЯ ПОПЫТКА', 'МОЛНИЯ', 'МАШИНА КЛИКОВ', 'ИДЕАЛЬНО'].map((name, index) => <article className={index > 2 ? 'locked' : ''} key={name}><Crown /><b>{name}</b><small>{index > 2 ? 'Заверши испытание со 100% точностью' : 'Получено'}</small></article>)}</div></section></main> }
function Daily({ play }: { play: (game: Game) => void }) { return <main className="listing daily-page"><span className="eyebrow"><span /> ИСПЫТАНИЕ ДНЯ · 11 СЕНТЯБРЯ</span><h1>Только один<br /><em>чистый шанс.</em></h1><p>Сегодняшний модификатор убирает все повторы. Засчитывается первая попытка.</p><div className="daily-card"><div><span>ТЕСТ РЕАКЦИИ</span><h2>Только одна попытка.</h2><button className="primary" onClick={() => play(games[0])}>Войти в испытание <ArrowRight /></button></div><b>01</b><div className="daily-meta">ТВОЙ РАНГ <strong>—</strong><br />УЧАСТНИКОВ В МИРЕ <strong>24 892</strong></div></div></main> }
function App() {
  const [path, setPath] = useState(() => window.location.pathname || '/');
  useEffect(() => { const onPop = () => setPath(window.location.pathname || '/'); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []);
  const navigate = (target: string) => { const routes: Record<string, string> = { home: '/', games: '/games', leaderboard: '/leaderboard', profile: '/profile', daily: '/daily' }; const next = routes[target] || target; if (next !== window.location.pathname) window.history.pushState({}, '', next); setPath(next); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const gameId = path.match(/^\/games\/([^/]+)$/)?.[1]; const game = games.find(item => item.id === gameId);
  const page = path === '/' ? 'home' : path.split('/')[1] || 'home';
  if (game) return <><Header page="games" setPage={navigate} /><GamePlay game={game} back={() => window.history.length > 1 ? window.history.back() : navigate('/games')} showLeaderboard={() => navigate(`/leaderboard?game=${game.id}`)} /></>;
  return <><Header page={page} setPage={navigate} />{page === 'home' ? <Home setPage={navigate} play={item => navigate(`/games/${item.id}`)} /> : page === 'games' ? <Games play={item => navigate(`/games/${item.id}`)} /> : page === 'leaderboard' ? <Leaderboard /> : page === 'profile' ? <Profile /> : page === 'daily' ? <Daily play={item => navigate(`/games/${item.id}`)} /> : <Home setPage={navigate} play={item => navigate(`/games/${item.id}`)} />}</>;
}
createRoot(document.getElementById('root')!).render(<App />);
