import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Crown, Flame, Gauge, Trophy, Volume2, Zap, Target, Keyboard, Brain, Music2, MousePointer2, Timer, ChevronRight, Check} from 'lucide-react';
import './style.css';

type Game={id:string,name:string,category:string,desc:string,icon:any,record:string,attempts:string,accent:string,mode:'reaction'|'click'|'aim'|'keyboard'|'rhythm'|'memory'|'numbers'|'color'|'mouse'|'arrows'};
const games:Game[]=[
{id:'reaction',name:'Reaction Test',category:'REACTION',desc:'Click the instant the signal turns live.',icon:Zap,record:'142 ms',attempts:'28.4k plays',accent:'#bdff64',mode:'reaction'},
{id:'click-speed',name:'Click Speed',category:'CLICK',desc:'Push your clicks per second to the edge.',icon:MousePointer2,record:'18.2 CPS',attempts:'18.9k plays',accent:'#ff9d5c',mode:'click'},
{id:'aim',name:'Aim Trainer',category:'PRECISION',desc:'Acquire targets before they disappear.',icon:Target,record:'96.8%',attempts:'16.2k plays',accent:'#8cf0ff',mode:'aim'},
{id:'keyboard',name:'Keyboard Rush',category:'SPEED',desc:'Type the sequence with zero hesitation.',icon:Keyboard,record:'142 WPM',attempts:'14.5k plays',accent:'#d5a6ff',mode:'keyboard'},
{id:'rhythm',name:'Rhythm Tap',category:'RHYTHM',desc:'Find the perfect moment in the pulse.',icon:Music2,record:'99.4%',attempts:'12.1k plays',accent:'#ff6b9a',mode:'rhythm'},
{id:'memory',name:'Memory Grid',category:'MEMORY',desc:'Recall the pattern as it gets denser.',icon:Brain,record:'Level 18',attempts:'9.8k plays',accent:'#ffc85c',mode:'memory'},
{id:'mouse-speed',name:'Mouse Flow',category:'COORDINATION',desc:'Trace the gates in a clean motion.',icon:Gauge,record:'4.82 s',attempts:'7.4k plays',accent:'#83a6ff',mode:'mouse'},
{id:'keyboard-reaction',name:'Arrow Reflex',category:'KEYBOARD',desc:'Mirror directional calls at speed.',icon:ChevronRight,record:'286 pts',attempts:'6.3k plays',accent:'#a0ffbd',mode:'arrows'},
{id:'numbers',name:'Number Sequence',category:'SPEED',desc:'Find every number in the right order.',icon:Timer,record:'3.18 s',attempts:'8.9k plays',accent:'#ffbb75',mode:'numbers'},
{id:'color-match',name:'Color Match',category:'FOCUS',desc:'Trust the color, not the word.',icon:Target,record:'1,240 pts',attempts:'5.6k plays',accent:'#ff86cd',mode:'color'}];
const leaderboard=[['Mira','12,482'],['n0va','12,108'],['kaizo','11,994'],['you','11,680'],['Lenn','11,251']];
function Header({page,setPage}:{page:string,setPage:(x:string)=>void}){return <><header><button className="brand" onClick={()=>setPage('home')}><i/> PULSE</button><nav>{['games','leaderboard','daily'].map(x=><button className={page===x?'active':''} onClick={()=>setPage(x)} key={x}>{x==='daily'?'Daily challenge':x[0].toUpperCase()+x.slice(1)}</button>)}</nav><div className="user"><span className="level">LVL 12 <b>Sharp</b></span><button onClick={()=>setPage('profile')} className="avatar">K</button></div></header><div className="mobile-nav">{['home','games','leaderboard','profile'].map(x=><button onClick={()=>setPage(x)} className={page===x?'active':''} key={x}>{x}</button>)}</div></>}
function Card({g,onPlay}:{g:Game,onPlay:()=>void}){let I=g.icon;return <article className="game-card" style={{'--accent':g.accent} as any} onClick={onPlay}><div className="card-top"><span>{g.category}</span><I size={19}/></div><div className="game-preview"><div className={'orb '+g.mode}/><div className="preview-lines"/></div><h3>{g.name}</h3><p>{g.desc}</p><footer><span>BEST <b>{g.record}</b></span><span>{g.attempts}</span></footer></article>}
function Home({setPage,play}:{setPage:(x:string)=>void,play:(g:Game)=>void}){return <main><section className="hero"><div className="eyebrow"><span/> THE HUMAN PERFORMANCE LAB</div><h1>How fast<br/>are <em>you?</em></h1><p>Test your reaction, speed, precision and coordination in short competitive challenges.</p><div className="hero-actions"><button className="primary" onClick={()=>play(games[0])}>Start a challenge <ArrowRight/></button><button className="quiet" onClick={()=>setPage('games')}>Explore all games</button></div><div className="hero-score"><div><small>YOUR SKILL SCORE</small><strong>782</strong><span>+24 this week</span></div><div className="radar">✦</div><div className="score-list"><span>REACTION <b>820</b></span><span>PRECISION <b>910</b></span><span>MEMORY <b>680</b></span></div></div></section><section className="featured"><div><span className="eyebrow"><span/> TODAY'S CHALLENGE</span><h2>One shot.<br/><em>Make it count.</em></h2><p>Reaction Test · only one attempt<br/>Resets in 08:42:16</p><button className="primary" onClick={()=>play(games[0])}>Take the challenge <ArrowRight/></button></div><div className="daily-number"><b>147</b><span>MS TO BEAT</span><i>TOP 5%</i></div></section><section className="section-title"><div><span className="eyebrow">POPULAR CHALLENGES</span><h2>Built for another run.</h2></div><button className="text-btn" onClick={()=>setPage('games')}>See all 10 games <ArrowRight size={16}/></button></section><section className="cards">{games.slice(0,6).map(g=><Card g={g} onPlay={()=>play(g)} key={g.id}/>)}</section><section className="split"><div className="leader"><div className="section-title"><div><span className="eyebrow">GLOBAL LEADERBOARD</span><h2>Chasing milliseconds.</h2></div><Trophy/></div>{leaderboard.map((r,i)=><div className={'rank '+(r[0]==='you'?'is-you':'')} key={r[0]}><b>0{i+1}</b><div className="avatar mini">{r[0][0]}</div><span>{r[0]}</span><strong>{r[1]} <small>PTS</small></strong></div>)}</div><div className="achievement"><Crown size={28}/><span className="eyebrow">NEXT UNLOCK</span><h3>UNSTOPPABLE</h3><p>Maintain a 7-day streak. You are 5 days in.</p><div className="progress"><i style={{width:'71%'}}/></div><small>5 / 7 DAYS</small></div></section><section className="cta"><span className="eyebrow">YOUR NEXT BEST</span><h2>Small games.<br/><em>Serious progress.</em></h2><button className="primary" onClick={()=>setPage('games')}>Start training <ArrowRight/></button></section></main>}
function Result({g,score,replay,close}:{g:Game,score:string,replay:()=>void,close:()=>void}){return <div className="result"><div className="result-icon"><Trophy/></div><span className="eyebrow">YOUR RESULT</span><h2>{score}</h2><p>Faster than <b>82%</b> of players</p><div className="pb"><Check/> NEW PERSONAL BEST <span>+18 XP</span></div><div className="result-stats"><span>GLOBAL RANK <b>#1,284</b></span><span>ACCURACY <b>96.8%</b></span><span>STREAK <b>4 DAYS</b></span></div><button className="primary" onClick={replay}>Play again <ArrowRight/></button><button className="quiet" onClick={close}>Back to games</button><small>Create an account to save your score.</small></div>}
function GamePlay({g,back}:{g:Game,back:()=>void}){const [state,setState]=useState<'idle'|'countdown'|'playing'|'result'>('idle');const [score,setScore]=useState('');const [count,setCount]=useState(0);const [target,setTarget]=useState({x:50,y:50});const [word,setWord]=useState('focus');const [tiles,setTiles]=useState<number[]>([0,2,4]);const start=useRef(0);const timer=useRef<number>(0);
 const finish=(s:string)=>{clearTimeout(timer.current);setScore(s);setState('result')}; const begin=()=>{setState('countdown');let n=3;let t=window.setInterval(()=>{n--; if(!n){clearInterval(t);setState('playing');start.current=performance.now(); if(g.mode==='reaction'){timer.current=window.setTimeout(()=>setWord('NOW'),1200+Math.random()*1500)} if(g.mode==='click')timer.current=window.setTimeout(()=>finish(`${(count/5).toFixed(1)} CPS`),5000)}},700)};
 useEffect(()=>{if(state!=='playing')return;const key=(e:KeyboardEvent)=>{if(g.mode==='keyboard'&&e.key==='Enter')finish('118 WPM');if(g.mode==='rhythm'&&e.code==='Space'){e.preventDefault();finish('94% accuracy')}if(g.mode==='arrows'&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)) {setCount(c=>{if(c+1===6)finish('286 points'); return c+1})}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[state,g.mode]);
 const clickReaction=()=>{if(word==='NOW')finish(`${Math.round(performance.now()-start.current)} ms`);else if(word!=='Get ready')finish('Too early!')}; const hit=()=>{let n=count+1;setCount(n);setTarget({x:10+Math.random()*80,y:12+Math.random()*72});if(n===8)finish('96.8%')};
 if(state==='result')return <GameFrame g={g} back={back}><Result g={g} score={score} replay={()=>{setCount(0);setWord('Get ready');setState('idle')}} close={back}/></GameFrame>;
 return <GameFrame g={g} back={back}><div className="game-stage">{state==='idle'&&<><span className="eyebrow">{g.category} · {g.id.toUpperCase()}</span><h2>{g.name}</h2><p>{g.desc}</p><button className="primary" onClick={begin}>Begin challenge <ArrowRight/></button><small>High precision timing · Sound on <Volume2 size={13}/></small></>}{state==='countdown'&&<div className="countdown">{3}<small>GET READY</small></div>}{state==='playing'&&<PlayUI g={g} count={count} target={target} word={word} setWord={setWord} clickReaction={clickReaction} hit={hit} finish={finish} setCount={setCount} tiles={tiles}/>}</div></GameFrame>}
function GameFrame({g,back,children}:{g:Game,back:()=>void,children:any}){return <main className="game-page"><div className="game-head"><button className="back" onClick={back}>← Exit</button><div><span>{g.category}</span><b>{g.name}</b></div><div className="sound"><Volume2 size={16}/> Sound</div></div>{children}</main>}
function PlayUI({g,count,target,word,setWord,clickReaction,hit,finish,setCount,tiles}:{g:Game,count:number,target:any,word:string,setWord:any,clickReaction:any,hit:any,finish:any,setCount:any,tiles:number[]}){if(g.mode==='reaction')return <button className={'reaction-zone '+(word==='NOW'?'live':'')} onClick={clickReaction}>{word}<small>{word==='NOW'?'CLICK NOW':'Wait for the signal'}</small></button>;
if(g.mode==='click')return <button className="click-zone" onClick={()=>setCount(count+1)}><b>{count}</b><span>CLICKS</span><small>Tap anywhere</small></button>;
if(g.mode==='aim')return <div className="aim-zone"><div className="aim-stats">SCORE <b>{count}/8</b> · COMBO <b>{count}</b></div><button aria-label="target" onClick={hit} className="target" style={{left:target.x+'%',top:target.y+'%'}}/></div>;
if(g.mode==='keyboard')return <div className="type-zone"><span>TYPE THIS SEQUENCE</span><b>focus · faster · sharper</b><input autoFocus placeholder="Press Enter when finished"/></div>;
if(g.mode==='rhythm')return <div className="rhythm-zone"><span>PRESS SPACE ON THE BEAT</span><div className="timing"><i/><b/></div><strong>● · · · ● · · ·</strong></div>;
if(g.mode==='memory')return <div className="memory-grid">{Array.from({length:9},(_,i)=><button className={tiles.includes(i)?'lit':''} onClick={()=>{if(tiles.includes(i)){setCount(count+1);if(count+1===3)finish('Level 4')}else finish('Level 2')}} key={i}/>)}</div>;
if(g.mode==='numbers')return <div className="number-grid">{[4,1,6,3,2,5,7,8,9].map(n=><button onClick={()=>{if(n===count+1){setCount(count+1);if(n===9)finish(`${((performance.now()-0)/1000).toFixed(2)} s`)} }} key={n}>{n}</button>)}</div>;
if(g.mode==='color')return <div className="color-zone"><strong style={{color:'#8cf0ff'}}>RED</strong><p>Choose the color of the word</p><div>{['BLUE','RED','GREEN','YELLOW'].map(x=><button onClick={()=>x==='BLUE'?finish('1,240 pts'):finish('Miss')}>{x}</button>)}</div></div>;
if(g.mode==='mouse')return <div className="mouse-zone"><p>Move through each gate in order</p>{[1,2,3,4].map(x=><button onMouseEnter={()=>{if(x===count+1){setCount(x);if(x===4)finish('4.82 s')}}} key={x}>{x}</button>)}</div>;
return <div className="arrows-zone"><span>Press the arrows in order</span><strong>↑ &nbsp; ↓ &nbsp; ↓ &nbsp; → &nbsp; ← &nbsp; ↑</strong><p>STREAK {count} / 6</p></div>}
function Games({play}:{play:(g:Game)=>void}){return <main className="listing"><span className="eyebrow">CHALLENGE LIBRARY</span><h1>Find your <em>edge.</em></h1><p>Ten focused tests. Each built to reveal a different part of your performance.</p><div className="filters"><button className="active">All games</button><button>Reaction</button><button>Precision</button><button>Speed</button><button>Memory</button></div><section className="cards all">{games.map(g=><Card g={g} onPlay={()=>play(g)} key={g.id}/>)}</section></main>}
function Leaderboard(){return <main className="listing leaderboard-page"><span className="eyebrow">LIVE RANKINGS</span><h1>Measure up<br/>to the <em>world.</em></h1><div className="board-tabs"><button className="active">Global</button><button>Weekly</button><button>Today</button></div><div className="board"><div className="board-head"><span>RANK</span><span>PLAYER</span><span>SKILL SCORE</span><span>STREAK</span></div>{leaderboard.concat([['Ayra','11,118'],['cedar','10,992'],['Vera','10,864']]).map((x,i)=><div className="board-row"><b>0{i+1}</b><div className="avatar">{x[0][0]}</div><strong>{x[0]} {x[0]==='you'&&<small>YOU</small>}</strong><span>{x[1]}</span><span><Flame size={15}/> {8-i} days</span></div>)}</div></main>}
function Profile(){return <main className="listing profile"><div className="profile-intro"><div className="avatar big">K</div><div><span className="eyebrow">PLAYER PROFILE</span><h1>kira<span>.pulse</span></h1><p>Sharp · Playing since September 2026</p></div><button className="quiet">Edit profile</button></div><section className="profile-score"><div><span>SKILL SCORE</span><strong>782</strong><small>TOP 18% · +24 THIS WEEK</small></div><div className="radar large">✦</div><div className="meters">{[['Reaction',82],['Speed',74],['Precision',91],['Memory',68],['Rhythm',76]].map(x=><label>{x[0]} <i><b style={{width:x[1]+'%'}}/></i> {x[1]}0</label>)}</div></section><div className="metrics">{[['42','GAMES PLAYED'],['214 ms','BEST REACTION'],['87%','AVG. ACCURACY'],['5 DAYS','CURRENT STREAK']].map(x=><div><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><section className="achievement-row"><span className="eyebrow">ACHIEVEMENTS · 6/24</span><div>{['FIRST TRY','LIGHTNING','CLICK MACHINE','PERFECT'].map((x,i)=><article className={i>2?'locked':''}><Crown/><b>{x}</b><small>{i>2?'Complete a challenge with 100% accuracy':'Unlocked'}</small></article>)}</div></section></main>}
function Daily({play}:{play:(g:Game)=>void}){return <main className="listing daily-page"><span className="eyebrow"><span/> DAILY CHALLENGE · SEPT 11</span><h1>Just one<br/><em>clean shot.</em></h1><p>Today's modifier removes all retries. Your first result is the result that counts.</p><div className="daily-card"><div><span>REACTION TEST</span><h2>Only one attempt.</h2><button className="primary" onClick={()=>play(games[0])}>Enter challenge <ArrowRight/></button></div><b>01</b><div className="daily-meta">YOUR RANK <strong>—</strong><br/>GLOBAL ENTRIES <strong>24,892</strong></div></div></main>}
function App(){const [page,setPage]=useState('home');const [selected,setSelected]=useState<Game|null>(null);const play=(g:Game)=>setSelected(g);return <><Header page={page} setPage={setPage}/>{selected?<GamePlay g={selected} back={()=>{setSelected(null);setPage('games')}}/>:page==='home'?<Home setPage={setPage} play={play}/>:page==='games'?<Games play={play}/>:page==='leaderboard'?<Leaderboard/>:page==='profile'?<Profile/>:<Daily play={play}/>}</>};createRoot(document.getElementById('root')!).render(<App/>);
